"""
Round 2 Dataset Catalog — FIFA World Cup Kaggle Sources
Produces:
  artifacts/wc_dataset_catalog_r2.csv   — the hero table
  artifacts/hero_catalog_r2.png/.svg    — the visualization
"""

import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import os

os.makedirs("artifacts", exist_ok=True)

# ── 1. CATALOG DATA ──────────────────────────────────────────────────────────
catalog = [
    # ── 2026 LIVE / PRIMARY ──────────────────────────────────────────────
    {
        "slug":             "mominullptr/fifa-world-cup-2026-dataset",
        "title":            "FIFA WC 2026 — Live Results & Stats",
        "era":              "2026",
        "category":         "2026 Primary",
        "tables":           11,
        "key_tables":       "matches(89×17), match_events(694×6), match_lineups(4576×7), match_team_stats(156×12), player_stats(1248×21), squads_and_players(1248×10), teams(48×8), venues(16×8)",
        "grain":            "match / player / event",
        "total_rows":       8263,
        "key_columns":      "date, stage, venue, home/away_team_id, score, possession_pct, shots, shots_on_target, corners; player: market_value_eur, goals, assists, pass_accuracy",
        "has_xg":           True,
        "has_player_dob":   True,
        "has_goalscorers":  True,
        "has_lineups":      True,
        "has_managers":     False,
        "has_referees":     True,
        "time_span":        "2026 only",
        "last_updated":     "2026-07-04",
        "freshness":        "daily",
        "license":          "CC0",
        "usability":        1.0,
        "downloads":        2168,
        "votes":            48,
        "quality_rating":   "A",
        "recommend":        "PRIMARY-2026",
        "traps":            "event table only has 694 rows (incomplete events); lineups is source of truth for player appearances; squads_and_players has all 1248 players with market_value_eur",
    },
    {
        "slug":             "swaptr/fifa-wc-2026-matches",
        "title":            "FIFA WC 2026 — Match Data (FBref-style)",
        "era":              "2026",
        "category":         "2026 Complement",
        "tables":           1,
        "key_tables":       "matches(89×42)",
        "grain":            "match",
        "total_rows":       89,
        "key_columns":      "formation, possession, shots, shots_on_target, corners, fouls, cards, xG per team",
        "has_xg":           True,
        "has_player_dob":   False,
        "has_goalscorers":  False,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "2026 only",
        "last_updated":     "2026-07-04",
        "freshness":        "daily",
        "license":          "CC0",
        "usability":        1.0,
        "downloads":        1177,
        "votes":            38,
        "quality_rating":   "A",
        "recommend":        "COMPLEMENT-2026",
        "traps":            "Match-level only; join to mominullptr on date+teams for player-level linkage",
    },
    {
        "slug":             "swaptr/fifa-wc-2026-players",
        "title":            "FIFA WC 2026 — Player Data (FBref-style)",
        "era":              "2026",
        "category":         "2026 Complement",
        "tables":           1,
        "key_tables":       "players(1248×72)",
        "grain":            "player (tournament totals)",
        "total_rows":       1248,
        "key_columns":      "xG, xA, plus_minus, GK stats (save_pct, clean_sheets), progressive carries/passes, fouls, discipline",
        "has_xg":           True,
        "has_player_dob":   False,
        "has_goalscorers":  False,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "2026 only",
        "last_updated":     "2026-07-04",
        "freshness":        "daily",
        "license":          "CC0",
        "usability":        1.0,
        "downloads":        1692,
        "votes":            43,
        "quality_rating":   "A",
        "recommend":        "COMPLEMENT-2026",
        "traps":            "Tournament cumulative totals only; no match-level breakdown",
    },
    {
        "slug":             "swaptr/fifa-wc-2026-teams",
        "title":            "FIFA WC 2026 — Team Data (FBref-style)",
        "era":              "2026",
        "category":         "2026 Complement",
        "tables":           1,
        "key_tables":       "teams(48×136)",
        "grain":            "team (tournament totals + vs. opponents)",
        "total_rows":       48,
        "key_columns":      "goals, assists, xG, GK stats (save_pct, clean_sheets_pct), pressing (fouls, tackles_won, interceptions), pens_won/conceded, plus_minus; all mirrored for opponent side",
        "has_xg":           True,
        "has_player_dob":   False,
        "has_goalscorers":  False,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "2026 only",
        "last_updated":     "2026-07-04",
        "freshness":        "daily",
        "license":          "CC0",
        "usability":        1.0,
        "downloads":        1167,
        "votes":            24,
        "quality_rating":   "A",
        "recommend":        "COMPLEMENT-2026",
        "traps":            "48 rows only; team-level aggregates; NEW in round 2 — missed in prior catalog",
    },
    {
        "slug":             "kkfkmf/fifa-world-cup-2026-whoscored-events",
        "title":            "FIFA WC 2026 — WhoScored Event Data (xT+VAEP)",
        "era":              "2026",
        "category":         "2026 Advanced",
        "tables":           20,
        "key_tables":       "event files per match (≈34MB total)",
        "grain":            "event (touch-level)",
        "total_rows":       None,
        "key_columns":      "xT, VAEP, event_type, player_id, minute, x/y coordinates",
        "has_xg":           True,
        "has_player_dob":   False,
        "has_goalscorers":  True,
        "has_lineups":      True,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "2026 group stage only (~20 matches as of Jun 29)",
        "last_updated":     "2026-06-29",
        "freshness":        "periodic",
        "license":          "unknown",
        "usability":        0.94,
        "downloads":        19,
        "votes":            1,
        "quality_rating":   "B",
        "recommend":        "ADVANCED-USE-ONLY",
        "traps":            "Group stage only; heavy processing required; incomplete coverage; 34 MB",
    },
    # ── HISTORICAL ALL-TIME ──────────────────────────────────────────────
    {
        "slug":             "piterfm/fifa-football-world-cup",
        "title":            "Football — FIFA WC 1930–2026 (piterfm)",
        "era":              "1930-2026",
        "category":         "Historical Primary",
        "tables":           5,
        "key_tables":       "matches(964×44), goalscorers_named, squads, player_stats, tournament_summary",
        "grain":            "match / player",
        "total_rows":       None,
        "key_columns":      "date, teams, score, xG (from ~2010), captains, named goalscorers, cards, subs, stadium, attendance",
        "has_xg":           True,
        "has_player_dob":   False,
        "has_goalscorers":  True,
        "has_lineups":      True,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "1930–2026",
        "last_updated":     "2026-06-10",
        "freshness":        "periodic",
        "license":          "CC-BY-NC-SA",
        "usability":        1.0,
        "downloads":        15880,
        "votes":            184,
        "quality_rating":   "A",
        "recommend":        "PRIMARY-HISTORICAL",
        "traps":            "xG only reliable from ~2010; CC-BY-NC-SA (no commercial use)",
    },
    {
        "slug":             "martj42/international-football-results-from-1872-to-2017",
        "title":            "International Football Results 1872–2026 (martj42)",
        "era":              "1872-2026",
        "category":         "Historical Primary",
        "tables":           3,
        "key_tables":       "results(49499×9), goalscorers(47855×8), shootouts(680×5)",
        "grain":            "match / goal / shootout",
        "total_rows":       98034,
        "key_columns":      "results: date, home_team, away_team, home_score, away_score, tournament, city, country, neutral; goalscorers: scorer, minute, own_goal, penalty; shootouts: winner, first_shooter",
        "has_xg":           False,
        "has_player_dob":   False,
        "has_goalscorers":  True,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "1872–2026",
        "last_updated":     "2026-07-03",
        "freshness":        "daily",
        "license":          "CC0",
        "usability":        1.0,
        "downloads":        148289,
        "votes":            2639,
        "quality_rating":   "A+",
        "recommend":        "PRIMARY-HISTORICAL",
        "traps":            "WC rows: 1058 matches, ~2973 goalscorer rows. Tournament field = 'FIFA World Cup' to filter. No lineup/xG data. HIGHEST VOTE COUNT of any WC dataset on Kaggle (2639). NEW in round 2.",
    },
    {
        "slug":             "joshfjelstul/world-cup-database",
        "title":            "World Cup Database 1930–2022 (joshfjelstul)",
        "era":              "1930-2022",
        "category":         "Historical Primary",
        "tables":           27,
        "key_tables":       "matches(900×37), goals(2548×27), players(7907×12+birth_date), player_appearances(18623×22), squads(10142×12), bookings(2466×26), substitutions(6464×24), penalty_kicks(279×19), managers(357×6), referees(380×9), stadiums(185×8), award_winners(132×12), host_countries(22×7), tournaments(21×18)",
        "grain":            "match / goal / player / booking / sub",
        "total_rows":       74979,
        "key_columns":      "birth_date for 7907 players; position (GK/DEF/MID/FWD); captain flag; minute_regulation+minute_stoppage for goals/bookings/subs; penalty_kick outcome; Wikipedia links; award winners (Golden Boot, Ball, Glove)",
        "has_xg":           False,
        "has_player_dob":   True,
        "has_goalscorers":  True,
        "has_lineups":      True,
        "has_managers":     True,
        "has_referees":     True,
        "time_span":        "1930–2022",
        "last_updated":     "2022-07-11",
        "freshness":        "archived",
        "license":          "CC-BY-SA-4.0",
        "usability":        0.88,
        "downloads":        2425,
        "votes":            24,
        "quality_rating":   "A+",
        "recommend":        "PRIMARY-HISTORICAL",
        "traps":            "Covers through Qatar 2022 only (no 2026). Most complete relational WC DB; best for manager/referee/award analysis. CC-BY-SA. NEW in round 2.",
    },
    {
        "slug":             "nawfeelrahman1124444/the-ultimate-fifa-world-cup-dataset-1930-to-2026",
        "title":            "Ultimate FIFA WC Dataset 1930–2026 (nawfeelrahman)",
        "era":              "1930-2026",
        "category":         "Historical Supplement",
        "tables":           12,
        "key_tables":       "team_stats(193×many), head_to_head(61 pairs), top_scorers_by_edition",
        "grain":            "team-edition / head-to-head pair",
        "total_rows":       None,
        "key_columns":      "appearances, wins, losses, draws, goals_for, goals_against, best_finish, H2H record between 61 WC rivalry pairs",
        "has_xg":           False,
        "has_player_dob":   False,
        "has_goalscorers":  True,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "1930–2026",
        "last_updated":     "2026-06-10",
        "freshness":        "periodic",
        "license":          "Apache-2.0",
        "usability":        1.0,
        "downloads":        791,
        "votes":            31,
        "quality_rating":   "B+",
        "recommend":        "SUPPLEMENT",
        "traps":            "Head-to-head only covers 61 pairs that actually met at WC; not all rivalries. Team-edition aggregates useful for cross-tournament comparisons.",
    },
    {
        "slug":             "darinhawley/fifa-world-cup-goalscorers-19302018",
        "title":            "FIFA WC Goalscorers Career Totals 1930–2018",
        "era":              "1930-2018",
        "category":         "Historical Supplement",
        "tables":           1,
        "key_tables":       "worldcupgoals(1295×7)",
        "grain":            "player career WC totals",
        "total_rows":       1295,
        "key_columns":      "player_name, country, goals, tournaments, year_range; top scorer = Klose (Germany) 16 goals",
        "has_xg":           False,
        "has_player_dob":   False,
        "has_goalscorers":  True,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "1930–2018",
        "last_updated":     "2021-11-09",
        "freshness":        "archived",
        "license":          "CC0",
        "usability":        1.0,
        "downloads":        None,
        "votes":            None,
        "quality_rating":   "B",
        "recommend":        "SUPPLEMENT",
        "traps":            "Through 2018 only (missing 2022+2026). Use martj42/goalscorers for more complete named goal data.",
    },
    {
        "slug":             "afonsofernandescruz/2026-fifa-world-cup-historical-elo-ratings",
        "title":            "WC 2026 Historical Elo Ratings (afonsocruz)",
        "era":              "1901-2026",
        "category":         "Context / Supplement",
        "tables":           1,
        "key_tables":       "elo_ratings_wc2026(4683×23)",
        "grain":            "country × year snapshot",
        "total_rows":       4683,
        "key_columns":      "year, snapshot_date, country, rank, rating, rank_max, rating_max, rank_avg, rating_avg, matches_total, wins, losses, draws, goals_for, goals_against, confederation, is_host",
        "has_xg":           False,
        "has_player_dob":   False,
        "has_goalscorers":  False,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "1901–2026 (48 WC-2026 teams only)",
        "last_updated":     "2026-05-27",
        "freshness":        "snapshot (pre-tournament)",
        "license":          "unclear",
        "usability":        1.0,
        "downloads":        2234,
        "votes":            37,
        "quality_rating":   "B+",
        "recommend":        "CONTEXT",
        "traps":            "Only 48 WC-2026 teams; pre-tournament snapshot (not updated with results); Elo from club football analogue not official FIFA ELO. NEW in round 2.",
    },
    {
        "slug":             "joebeachcapital/fifa-world-cups",
        "title":            "FIFA WC Player z-Score Comparisons (joebeachcapital)",
        "era":              "2010-2022",
        "category":         "Historical Supplement",
        "tables":           1,
        "key_tables":       "world_cup_comparisons(5886×19)",
        "grain":            "player × tournament",
        "total_rows":       5886,
        "key_columns":      "player, season, team, z-scores: goals_z, xg_z, crosses_z, boxtouches_z, passes_z, progpasses_z, takeons_z, progruns_z, tackles_z, interceptions_z, clearances_z, blocks_z, aerials_z, fouls_z, fouled_z, nsxg_z",
        "has_xg":           True,
        "has_player_dob":   False,
        "has_goalscorers":  False,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "~2010–2022",
        "last_updated":     "2023-08-23",
        "freshness":        "archived",
        "license":          "unclear",
        "usability":        1.0,
        "downloads":        1594,
        "votes":            47,
        "quality_rating":   "B",
        "recommend":        "SUPPLEMENT",
        "traps":            "z-scores normalized within each tournament edition; not raw stats. Best for cross-edition player ranking, not absolute metrics. NEW in round 2.",
    },
    {
        "slug":             "die9origephit/fifa-world-cup-2022-complete-dataset",
        "title":            "FIFA WC 2022 — Tactical Match Stats (die9origephit)",
        "era":              "2022",
        "category":         "Historical Supplement",
        "tables":           1,
        "key_tables":       "matches(64×88)",
        "grain":            "match (both teams side by side)",
        "total_rows":       64,
        "key_columns":      "line_breaks attempted/completed, offers_to_receive (in-behind/between/in-front), channel attacks (left/central/right), defensive_pressures_applied, possession_in_contest, goal_preventions",
        "has_xg":           False,
        "has_player_dob":   False,
        "has_goalscorers":  False,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "2022 only",
        "last_updated":     "2022-12-18",
        "freshness":        "archived",
        "license":          "unknown",
        "usability":        1.0,
        "downloads":        24627,
        "votes":            414,
        "quality_rating":   "B+",
        "recommend":        "SUPPLEMENT",
        "traps":            "2022 Qatar WC only; 88-column wide-format (both teams as columns). Unique tactical metrics from FIFA data portal not available in other datasets. NEW in round 2.",
    },
    {
        "slug":             "velvetcrystal/fifa-world-cup-2026-complete-tournament-statistics",
        "title":            "FIFA WC 2026 Complete Tournament Stats (velvetcrystal)",
        "era":              "2026",
        "category":         "2026 Complement",
        "tables":           3,
        "key_tables":       "matches(104×32), players(3328×15), team_stats(48×12)",
        "grain":            "match / player-match / team",
        "total_rows":       3480,
        "key_columns":      "matches: xG, weather, attendance, FIFA_rank; players: per-match rating, minutes_played, tackles, interceptions, saves",
        "has_xg":           True,
        "has_player_dob":   False,
        "has_goalscorers":  False,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "2026 (stale since Jun 20)",
        "last_updated":     "2026-06-20",
        "freshness":        "stale",
        "license":          "MIT",
        "usability":        1.0,
        "downloads":        599,
        "votes":            61,
        "quality_rating":   "C+",
        "recommend":        "SECONDARY",
        "traps":            "Last updated 2026-06-20; missing recent knockout-stage matches. Player ratings appear synthetic (uniform distribution). Prefer mominullptr+swaptr for current data. NEW in round 2.",
    },
    # ── DO NOT USE ──────────────────────────────────────────────────────
    {
        "slug":             "rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset",
        "title":            "FIFA WC 2026 Player Performance (SYNTHETIC — DO NOT USE)",
        "era":              "2026 (fabricated)",
        "category":         "SYNTHETIC — REJECT",
        "tables":           1,
        "key_tables":       "player_performance(54600×75)",
        "grain":            "player × match",
        "total_rows":       54600,
        "key_columns":      "distance_covered_km, sprint_distance_km, top_speed_kmh, stamina_score, creativity_score (all synthetic)",
        "has_xg":           True,
        "has_player_dob":   False,
        "has_goalscorers":  False,
        "has_lineups":      False,
        "has_managers":     False,
        "has_referees":     False,
        "time_span":        "2026-06-11 to 2026-07-31 (impossible: future dates)",
        "last_updated":     "2026-06-10",
        "freshness":        "synthetic",
        "license":          "unknown",
        "usability":        1.0,
        "downloads":        7390,
        "votes":            170,
        "quality_rating":   "F",
        "recommend":        "REJECT",
        "traps":            "⚠️ SYNTHETIC DATA: 1050 unique match_ids impossible (only 104 WC2026 games); dates extend to 2026-07-31 (future); player names are composites (e.g. 'Rodri Fati', 'Ansu Le Normand'); GPS/biometric metrics not available publicly. HIGH DOWNLOAD COUNT but FABRICATED. Do not use for any factual analysis.",
    },
]

df = pd.DataFrame(catalog)
df.to_csv("artifacts/wc_dataset_catalog_r2.csv", index=False)
print(f"Catalog: {len(df)} datasets × {len(df.columns)} columns")
print(df[["slug","quality_rating","recommend","total_rows","tables","era"]].to_string())
